### PR TITLE
Fix extension installation reporting

### LINKED ISSUE #371: Diagnose report successfull install on download, not on installation
I noticed in [this conversation](https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/mentions/conversations/16410700029272) that the musl build doesn't work, see #29.

Based on the diagnose report I had the idea it was successfully installed because it reported "success" for "status". Looks like it's set to "success" if it managed to download the agent and extension package, not when it actually finished installing. We need to change it to only report it as "installed" when it's done installing.

https://github.com/appsignal/appsignal-nodejs/blob/92c1b952c9acc8a053176ee0872ac7ed953b2517/packages/nodejs-ext/scripts/extension.js#L143

### PR DESCRIPTION
**Pull request by tombruijn**
When the extension installed we never stored if it installed correctly
or not. Originally it would always report it as a "success" status. In a
previous commit cb08b7a16c4f81239724a1f71ac99371015b568e, PR #373, I
changed the report status to "unknown", because after the `extension.js`
script was run the `node-gyp rebuild` command was run through the
`package.json` `install` script. After the node-gyp command was run it
would not return to the extension.js script and we couldn't check the
exit status of that command.

Instead of running the node-gyp command after the `extension.js` script,
run the node-gyp command from the `extension.js` script so we can listen
to the exit status and report the installation as a success or "error"
when it encounters an error.

This should fix #371, the issue describing the scenario above, the
install report not accurately describing the installation status.

I am not sure why the originally implementation was chosen. The original
implementation was present since the initial commit of the project.
There may be a problem with this new implementation that I am unaware of
now, because I'm no Node.js expert. But we call out to other commands
like `tar` from the `extension.js` script as well, so I figure it will
be fine.

## CI build update

I've added tests for the extension build failure scenario, and the
success scenario. For this I needed to have Jest run certain specs only
some of the time, based on the `_TEST_APPSIGNAL_EXTENSION_FAILURE`
environment variable (same as in the Ruby gem CI setup). This is done
with the `--filter` option (which links to a file with a filter
function), which is configured through the `package.json` test scripts.

Since these new tests are only for the `nodejs-ext` package I found it
unnecessary to spin up a new job for it, and instead add it as
`extra_commands` to the package's test commands.

Before the failure state is tested, the extension installation is
cleaned up, so it doesn't think it has installed correctly.

Because we install the extension in the "Build" task, and it's not
present in the project dir, but instead the `/tmp` dir on the system,
I've also copied the report location from the "Build" task to the job
that tests this report. Otherwise it would fail on a missing file, or
we'd need to install the extension again. Hopefully we can find a better
location for the install report location in issue #372.

### CODE REVIEW

File: packages/nodejs-ext/scripts/extension.js [hunk 1]
```diff
@@ -21,9 +21,15 @@ const {
 } = require("./report")
 
 const EXT_PATH = path.join(__dirname, "/../ext/")
+const testExtensionFailure =
+  process.env._TEST_APPSIGNAL_EXTENSION_FAILURE == "true"
```
Comment (tombruijn) [inline packages/nodejs-ext/scripts/extension.js:25]:
```suggestion
  process.env._TEST_APPSIGNAL_EXTENSION_FAILURE === "true"
```

File: packages/nodejs-ext/test/filter.js [hunk 2]
```diff
@@ -0,0 +1,25 @@
+"use strict"
+
+const testExtensionFailure =
+  process.env._TEST_APPSIGNAL_EXTENSION_FAILURE == "true"
```
Comment (tombruijn) [inline packages/nodejs-ext/test/filter.js:4]:
```suggestion
  process.env._TEST_APPSIGNAL_EXTENSION_FAILURE === "true"
```

**Review by jeffkreeftmeijer — APPROVED** [review]
